### PR TITLE
Make filename optional in get command.

### PR DESCRIPTION
**Pull request by marcosnils**
If filename is not specified vault will use the same filename as the one to decrypt

@xetorthio plz review.

### CODE REVIEW

**Comment by xetorthio** [comment]
I don't really understand how this could be used. 
For example I have in my vault:
`foo/bar/car.asc`

You say I can do this?
```
vault get -o foo/bar/car
```

And I would get a file called `car` in `foo/bar`  with the decrypted content of `car.asc`?

**Comment by marcosnils** [comment]
Exactly. 

That way you don't have to do this `vault get -o /foo/bar/car /foo/bar/car.asc`. If you omit the output filename it will use the same one as the decrypted but without the asc extension.

**Comment by xetorthio** [comment]
Mmm... it is weird... I always saw it the other way around.
You specify the input file, and output file is inferred. Inferring the input file from the output file is weird.

**Comment by marcosnils** [comment]
You're right, this is not necessary.

**Pull request closed without merging**
